server:
  port: 51200

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingdb
    username: admin
    password: password  # Asegurate de ajustar esto segun tu local
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:50003 # URL de tu auth-service
  cloud:
    discovery:
      client:
        simple:
          instances:
            movie-service:
              - uri: http://localhost:51100

# Nombre de servicio que resuelve @LoadBalanced (no es una URL directa):
movie-service:
  url: http://movie-service

# Configuración de resiliencia requerida por la rúbrica
retry:
  max-attempts: 3
  backoff-delay: 500

springdoc:
  swagger-ui:
    path: /api/v1/swagger-ui.html
